# Generated by Django 6.0 on 2026-01-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
