# Generated by Django 6.0 on 2026-01-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('science', 'Science'), ('technology', 'Technology'), ('health', 'Health'), ('politics', 'Politics'), ('business', 'Business')], default='science', max_length=20),
        ),
    ]
