# Generated by Django 6.0 on 2026-01-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
