# Generated by Django 6.0 on 2026-01-19 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
